[9.0][MIG][crm_lead_website] Websites in leads.
OCA/crm pull request #113
Opened 2016-09-30 13:23 UTC by Yajo

Now available for v9.

This commit includes all adaptations to v9, and some to new OCA guidelines.

@Tecnativa

2016-09-30 14:30 UTC, pedrobaeza requested changes

2016-09-30 14:30 UTC, pedrobaeza commented on crm_lead_website/README.rst
> +* Rafael Blasco <rafaelbn@antiun.com>
Change emails to new ones

2016-09-30 14:30 UTC, pedrobaeza commented on crm_lead_website/models/crm_lead.py
> +            if self.partner_id and self.partner_id.website:
You can't use `self.partner_id`, as old onchange API methods doesn't guarantee that self is the current recordset. You need to make a browse. Once done, you can query directly `partner_id.website`

2016-10-04 06:24 UTC, atchuthan approved these changes
Tested in Runbot :+1:

2016-10-04 14:32 UTC, rafaelbn approved these changes
Review comments functionally it's OK

2016-10-10 15:10 UTC, pedrobaeza approved these changes

2016-10-10 15:10 UTC, pedrobaeza commented
Waiting for CIs to merge.

2016-10-10 16:51 UTC, merged