9.0 [MIG] crm_deduplicate_acl migration
OCA/crm pull request #122
Opened 2016-11-07 11:23 UTC by cubells

2016-11-08 00:02 UTC, pedrobaeza commented
Check Travis error:
```
crm_deduplicate_acl/wizards/partner_merge.py:22:29: E131 continuation line unaligned for hanging indent
```

2016-11-09 13:42 UTC, yajo requested changes

2016-11-09 13:42 UTC, Yajo commented on crm_deduplicate_acl/wizards/partner_merge.py
> +                .ids else self.env.uid,
I think you should use `self.env.user.has_group` instead.

2016-11-29 00:50 UTC, pedrobaeza approved these changes

2016-11-30 08:20 UTC, yajo approved these changes
Code review.

2016-11-30 10:24 UTC, rafaelbn approved these changes
Thanks

2016-11-30 10:33 UTC, rafaelbn commented
@cubells one question, where is the functionality of "deduplicate" in v9? in which menu? thanks

2016-11-30 11:22 UTC, rafaelbn submitted a review, later dismissed
@cubells one question, where is the functionality of "deduplicate" in v9? in which menu? thanks

2016-11-30 12:45 UTC, cubells commented
v8.0 menu doesn't exist in version 9.0.

Module now only inherits wizard to merge partner.

2016-11-30 13:18 UTC, rafaelbn commented
I think we should recover this menu item. This is a functionality that without this menu item lost a lot.

2016-11-30 13:20 UTC, cubells commented
I can create a new menu if you want, as the parent menu of version 8.0 has disappear in v.9.0.

2016-11-30 13:36 UTC, cubells commented
Sorry Rafa: menu disappear in crm module. I think It's better do a PR in crm module:

https://github.com/OCA/OCB/blob/8.0/addons/crm/base_partner_merge_view.xml#L16

2016-11-30 14:13 UTC, rafaelbn commented
I agree @cubells with a PR to CRM module. Let see what @pedrobaeza thinks about this

2016-11-30 15:03 UTC, pedrobaeza commented
It was removed here https://github.com/odoo/odoo/commit/30a7ef804a1457fb0274994993c86a01dbb114d4#diff-be356a586330623cb55dac5cdf755b17L15 without apparent reason. I have asked if Odoo would accept a PR amending this in a commit that fixes some things of that commit: https://github.com/odoo/odoo/commit/876634b1dabb64414df1558d4ef0e99db8185f73.

If not, we should add here that menu, and depend on this one for other modules that improves deduplication wizard features (like _crm_deduplicate_by_website_ or  _crm_deduplicate_filter_).

2016-12-05 19:06 UTC, pedrobaeza commented
Please include the menu as there's no answer.

2016-12-06 10:46 UTC, merged