[9.0][ADD][WIP] crm_phonecall module
OCA/crm pull request #131
Opened 2017-01-24 05:23 UTC by cubells

Extracted model from crm module to manage phone calls.
Addition is needed for users who want to analyze those calls, impute times and much more.

WIP because I'm working on tests now.

2017-01-31 13:22 UTC, pedrobaeza requested changes
Excellent work extracting, passing to new API and testing some parts. A little more to do in my comments for improving still more and we were good to go.

2017-01-31 13:22 UTC, pedrobaeza commented on crm_phonecall/README.rst
> +* Vicent Cubells <vicent.cubells@tecnativa.com>
Put Odoo S. A.

2017-01-31 13:22 UTC, pedrobaeza commented on crm_phonecall/__init__.py
> +##############################################################################
Use new header style

2017-01-31 13:22 UTC, pedrobaeza commented on crm_phonecall/__openerp__.py
> +    "author": "Tecnativa, "
Include Odoo S. A.

2017-01-31 13:22 UTC, pedrobaeza commented on crm_phonecall/models/res_partner.py
> +        copy=False,
Being computed, copy and default are ignored.

2017-01-31 13:22 UTC, pedrobaeza commented on crm_phonecall/report/crm_phonecall_report.py
> +AVAILABLE_STATES = [
Why don't you take it from the same source instead of creating the list 2 times?

2017-01-31 13:22 UTC, pedrobaeza commented on crm_phonecall/report/crm_phonecall_report.py
> +            create or replace view crm_phonecall_report as (
Make this report inheritable extracting the SQL parts in methods as you already seen in for example invoices.

2017-01-31 13:22 UTC, pedrobaeza commented on crm_phonecall/wizard/crm_phonecall_to_phonecall.py
> +            if 'name' in fields:
You can do here a loop here for avoiding too much code:
```
for field in ('name', 'user_id'...):
    if field in fields:
        res[field] = getattr(phonecall, field)
```

2017-01-31 13:22 UTC, pedrobaeza commented on crm_phonecall/wizard/crm_phonecall_to_phonecall.py
> +                this.user_id.id or False,
No need of the `or False`

2017-01-31 16:44 UTC, pedrobaeza commented
Other comment from migration (for at least avoiding a crash):

* Rename on a migration script the group called "Show Scheduled Calls Menu" (`group_scheduled_calls`)

2017-01-31 17:44 UTC, pedrobaeza commented
Another thing: you need to rename ir.filters from crm.phonecall.report or there will be a duplicated name error.

2017-01-31 19:02 UTC, cubells commented on crm_phonecall/report/crm_phonecall_report.py
> +AVAILABLE_STATES = [
This list is created only one time.

2017-02-01 19:49 UTC, cubells commented
I'll rebase on pass tests...

2017-03-01 03:04 UTC, rafaelbn commented on crm_phonecall/README.rst
> +   Configuration > Leads & Opportunities > Phone Calls > Categories*.
Why this option is only available with debub mode? You have to Activate the developer mode to see this... Could you change it please? it doesn't have any sense as a user "never" Activate the developer mode.

2017-03-01 17:41 UTC, alexcbr2 reviewed
Functionallity checked but you can only access Sales >
 Configuration > Leads & Opportunities > Phone Calls > Categories if you are in developer mode.

2017-03-18 16:20 UTC, pedrobaeza commented
@cubells please attend remaining comments.

2017-03-24 14:21 UTC, cubells commented
@rafaelbn @pedrobaeza 

all is done.
cc @Tecnativa

2017-03-24 15:44 UTC, rafaelbn approved these changes

2017-03-24 15:48 UTC, pedrobaeza approved these changes

2017-03-24 15:53 UTC, luismontalba approved these changes
Tested on runbot

2017-03-24 16:02 UTC, merged