[9.0][MIG] crm_phonecall_summary_predefined module
OCA/crm pull request #132
Opened 2017-01-31 04:19 UTC by cubells

- Updated views
- Updated README

WIP because depends on https://github.com/OCA/crm/pull/131

cc @Tecnativa

2017-01-31 13:11 UTC, pedrobaeza requested changes

2017-01-31 13:11 UTC, pedrobaeza commented on crm_phonecall_summary_predefined/models/crm_phonecall.py
> +        self._init_summary_id(cr, SUPERUSER_ID)
This should be done as a post_init_hook, not with this hacky technique from old times.

2017-01-31 18:17 UTC, pedrobaeza commented on crm_phonecall_summary_predefined/views/crm_phonecall_view.xml
> +        <field name="inherit_id" ref="crm_phonecall.crm_case_inbound_phone_tree_view"/>
Don't put `crm_phonecall` in all of these XML-IDs

2017-01-31 18:19 UTC, pedrobaeza commented on crm_phonecall_summary_predefined/views/crm_phonecall_view.xml
> +        <field name="inherit_id" ref="crm_phonecall.crm_case_inbound_phone_tree_view"/>
Sorry, it has been a mistake by my part

2017-02-27 16:20 UTC, rafaelbn commented
Please @cubells could you review travis? thanks

2017-02-27 16:36 UTC, cubells commented
@rafaelbn 
Travis error is due to crm_phonecall dependency.

We have tot wait until #131 was merged.

2017-03-24 15:30 UTC, pedrobaeza commented
@cubells please fix this one.

2017-03-28 18:02 UTC, pedrobaeza commented on crm_phonecall_summary_predefined/models/crm_phonecall.py
> +        self._init_summary_id(cr, SUPERUSER_ID)
@cubells this is not fixed

2017-03-31 05:03 UTC, rafaelbn commented
Please @cubells could you review this PR for testing

2017-04-01 14:28 UTC, pedrobaeza approved these changes

2017-04-01 14:28 UTC, pedrobaeza commented
@chienandalu @luismontalba this one is ready to be reviewed

2017-04-03 08:37 UTC, luismontalba commented on crm_phonecall_summary_predefined/README.rst
> +
To configure the possible summary aptions, activate the developer mode and go to:

2017-04-03 08:40 UTC, luismontalba commented on crm_phonecall_summary_predefined/README.rst
> +
*  Go to *Sales > Configuration > Sales & Opportunities > Phone calls > Summaries*.

2017-04-03 08:43 UTC, luismontalba reviewed
Functionality tested on runbot. Please review minor changes proposed in configuration instructions.

2017-04-03 09:04 UTC, chienandalu approved these changes
functionality tested on runbot

2017-05-05 10:05 UTC, luismontalba approved these changes

2017-05-11 13:17 UTC, merged