[10.0] fix crm_claim import
OCA/crm pull request #186
Opened 2017-11-10 18:04 UTC by BenjaHe

The "import" in the line 65 "selection=odoo.addons.base.res.res_request.referenceable_models," broke my environment.

I propose to make the import on the top of the file.

2017-11-10 18:50 UTC, pedrobaeza commented
@cubells please check and see the Travis error.

@BenjaHe please sign the CLA

2017-11-11 15:00 UTC, BenjaHe commented
@pedrobaeza I did it yesterday evening and send it to cla at https://odoo-community.org as mentioned

2017-11-13 09:44 UTC, yajo requested changes

2017-11-13 09:44 UTC, Yajo commented on crm_claim/models/crm_claim.py
>  import odoo
The linter tells you to remove this now: https://travis-ci.org/OCA/crm/jobs/300289352#L738

2017-11-24 10:01 UTC, igallart commented
This commit is necessary. I have installed Odoo 10 and it not work, internal server.

2017-12-04 15:36 UTC, cubells approved these changes
I've got no error with old code. Tested and retested, but with these changes either.

LGTM

👍

2017-12-04 15:38 UTC, pedrobaeza commented
@Yajo's comment has been honored, so I merge.

2017-12-04 15:39 UTC, merged