11.0 mig crm claim type
OCA/crm pull request #193
Opened 2018-02-20 15:26 UTC by larmar

I have upgraded this version 11

2018-02-20 18:39 UTC, pedrobaeza commented
Thanks, please squash together "OCA Transbot..." commits that can be joined.

2018-02-21 06:09 UTC, larmar commented
Should 
[FIX] remove en.po that was erroneously created by transbot [Stéphane Bidoul (ACSONE)] also be squashed in Transbot
Or leave one Transibot before and one after ?

2018-02-21 08:49 UTC, pedrobaeza commented
Yes, please squash it also.

2018-04-12 15:36 UTC, keshrath requested changes
Exception: Module loading crm_claim_type failed: file crm_claim_type\security/ir.model.access.csv could not be processed:
No matching record found for external id 'base.group_sale_manager' in field 'Group'
No matching record found for external id 'base.group_sale_salesman' in field 'Group'

--> sales_team.group_sale_manager
--> sales_team.group_sale_salesman

odoo.tools.convert.ParseError: "FEHLER:  NULL-Wert in Spalte »name« verletzt Not-Null-Constraint
DETAIL:  Fehlgeschlagene Zeile enthält (317, null, ir.actions.act_window, null, null, action, 1, 2018-04-12 15:34:05.916973, 1, 2018-04-12 15:34:05.916973, null, null, 
                {"search_default_user_id":uid, "stage_type":'cl..., null, null, null, current, tree,form, form, null, 80, null, f, t, f).
" while parsing file:/c:/users/mathias/workspace/crm_claim_type/views/crm_claim_stage.xml:4, near
```
<record id="crm_claim.crm_case_categ_claim0" model="ir.actions.act_window">
            <field name="context">
                {"search_default_user_id":uid, "stage_type":'claim'}
            </field>
        </record>
```

2019-09-24 13:03 UTC, ecino commented
What's the status of this?

2019-09-24 15:56 UTC, MeetKD reviewed
If you are going to work on it please attend this minor comment.

2019-09-24 15:56 UTC, MeetKD commented on crm_claim_type/__manifest__.py
> +              'Ursa Information Systems',
I guess OCA as author should be at last.

2019-11-19 10:35 UTC, quentingigon commented
Will this module be merged soon ?

2019-11-25 11:25 UTC, ecino commented
@eicher31 Could you test and review this one as well?

2022-01-09 12:31 UTC, closed without merging