[MIG] Migrating crm_location to v11
OCA/crm pull request #201
Opened 2018-04-30 04:28 UTC by hprasetyou

2018-04-30 10:04 UTC, pedrobaeza commented
Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

2018-06-09 20:06 UTC, MeetKD requested changes

2018-06-09 20:06 UTC, MeetKD commented on crm_location/__manifest__.py
> +    'website': 'https://www.tecnativa.com',
Change website key https://github.com/OCA/crm

2018-06-09 20:06 UTC, MeetKD commented on crm_location/views/crm_lead_view.xml
> +        </field>
Minor suggestion placeholder should be select city/location/zip.

2019-09-01 22:40 UTC, rafaelbn commented
Hi @hprasetyou , thanks you this PR. Please are you going to fix it? Thanks!

2022-01-09 12:31 UTC, closed without merging