[WIP][10.0] Create module crm_lead_partner_role
OCA/crm pull request #204
Opened 2018-06-08 16:39 UTC by grindtildeath

2018-06-11 14:42 UTC, grindtildeath commented
@sbidoul I cannot find any up to date explanation on what's to do now with the new README.rst generation feature.
It seems https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#readme is still to be updated.
However, I did add `readme` folder with `DESCRIPTION.rst` and `CONTRIBUTORS.rst` as explained on  https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst but travis now complains there's no README.rst. Should I simply add an empty file ? Is there anything I am missing somewhere ?

2018-06-11 15:06 UTC, sbidoul commented
@grindtildeath yes a dummy README.rst is fine, it will be overwritten nightly

2018-06-12 07:05 UTC, simahawk requested changes

2018-06-12 07:05 UTC, simahawk commented on crm_lead_partner_role/models/crm_partner_role.py
> +    _name = 'crm.partner.role'
_description

2018-06-12 07:05 UTC, simahawk commented on crm_lead_partner_role/models/crm_role.py
> +
_description

2018-06-12 07:05 UTC, simahawk commented on crm_lead_partner_role/models/crm_lead.py
> +    partner_role_ids = fields.One2many(
help="Partners involved on this lead and their roles." (or alike)

2018-06-12 07:05 UTC, simahawk commented on crm_lead_partner_role/readme/DESCRIPTION.rst
> +This module can then be extend to process these data when converting to
extended

2018-06-12 07:41 UTC, simahawk approved these changes

2018-06-12 11:47 UTC, fclementic2c commented
Functional test Ok
:+1:

2018-06-13 07:50 UTC, simahawk commented
@sbidoul @grindtildeath I still see 
```
2018-06-12 08:01:21,841 193 WARNING openerp_test odoo.addons.base.module.module: module crm_lead_partner_role: description is empty !
```
Linting should be fixed too ;)

2018-07-12 15:24 UTC, tschanzt approved these changes

2019-09-01 23:08 UTC, rafaelbn reviewed
Hi @grindtildeath @simahawk @tschanzt ,

I have been testgin in runbot :red_circle: (we should ensure runbot is green :green_heart: ) and I was trying to find where a can Assign partner and roles to your leads... Could you please tell me how?

Thanks

2019-09-01 23:11 UTC, rafaelbn commented
![2019-09-02_1-10-54](https://user-images.githubusercontent.com/8736623/64083328-94c28600-cd1e-11e9-88ad-59ef42d58e14.png)

2019-09-02 08:08 UTC, grindtildeath commented
@rafaelbn as written in the readme there's a new tab on crm.lead:
![image](https://user-images.githubusercontent.com/778828/64099468-a7ae7800-cd69-11e9-9f20-291fa8a248ca.png)

2019-09-02 08:11 UTC, rafaelbn commented
OK thanks. Then please review Readme as it looks it doesn't generate well and after is inaccesible as you can see in my screenshot. I've tested the module 👍 
So just the Readme for merging! :-)

2019-09-02 08:12 UTC, rafaelbn commented
Ups, also please review bots! Are 🔴

2019-09-02 18:02 UTC, rafaelbn approved these changes

2019-09-02 18:03 UTC, rafaelbn commented
/ocabot merge

2019-09-02 18:45 UTC, closed without merging