[10.0][mig][crm_partner_schedule_meeting]
OCA/crm pull request #209
Opened 2018-06-20 11:54 UTC by jbeficent

Migration from https://github.com/OCA/crm/pull/208

CRM Partner Schedule Meeting
============================

This module allows to display the meetings of a company as the sum of all
the meetings held with the company's contacts.

2018-06-20 11:56 UTC, pedrobaeza commented
What is the advantage of this over checking the "All" calendar?

2018-06-20 12:02 UTC, jbeficent commented
@pedrobaeza When you go to a partner, say "Eficent", you want to see how many meetings are scheduled with Eficent's individual persons, because as a general rule no one meets with Eficent as a company.

2018-06-20 12:07 UTC, pedrobaeza commented
OK, got it. I was thinking on the company, not on the partner side. But this is not correctly put nor named. It should be `calendar_commercial_partner` or `calendar_commercial_partner_meeting`, and be relocated to OCA/calendar, not here.

2018-06-20 12:15 UTC, jbeficent commented
But this feature depends on module `crm`, not `calendar.` That's why I suggested it here

2018-06-20 12:17 UTC, pedrobaeza commented
I think you should go more for the generic one (these CRM meetings are also calendar meetings).

2018-11-07 15:54 UTC, jbeficent commented
@pedrobaeza This module builds on top of a feature to display the partner's meetings that is introduced by odoo in the CRM module.
https://github.com/odoo/odoo/blob/10.0/addons/crm/models/res_partner.py#L37
https://github.com/odoo/odoo/blob/10.0/addons/crm/views/res_partner_views.xml#L119

It's all over the crm module.

What this module does is to extend the methods to allow the user to view all the meetings from a company perspective, to have an overall view of all meetings scheduled with individual contacts.

By removing the dependency with crm we would duplicate the features.

2018-11-07 23:27 UTC, pedrobaeza commented
Ok, let's go this way.

2018-11-08 08:46 UTC, LoisRForgeFlow approved these changes
LGTM :+1:

2018-11-08 09:02 UTC, jbeficent commented
@Beji94 @ageficent can you test this on runbot? @lreficent can help you.

2018-11-09 10:49 UTC, AdriaGForgeFlow requested changes
Odoo crashing on startup due to crm_partner_shcedule_meeting/ folder.

2018-11-09 10:49 UTC, ageficent commented on crm_partner_schedule_meeting/__manifest__.py
> +# -*- encoding: utf-8 -*-
I think this file does not belong here. It makes Odoo crash. Solved deleting the folder.

2018-11-12 11:39 UTC, lreficent commented
@ageficent It's fixed, could you update your review?

2018-11-12 11:58 UTC, AdriaGForgeFlow approved these changes
LGTM

2018-11-13 16:07 UTC, merged