[12.0] [MIG] crm_phonecall_summary_predefined
OCA/crm pull request #252
Opened 2018-12-22 07:56 UTC by anandkansagra

Issue [Reference](https://github.com/OCA/crm/issues/232)

2018-12-22 11:29 UTC, pedrobaeza commented
Please squash together adjacent "[UPD] Update crm_phonecall_summary_predefined.pot" commits and check runbot status.

2018-12-22 13:38 UTC, anandkansagra commented
> Please squash together adjacent "[UPD] Update crm_phonecall_summary_predefined.pot"

Done

>  commits and check runbot status.

Well regarding that, took a pull from the remote 12.0 branch which has `crm_phonecall` module. In the runbot log, couldn't find why it has not passed. Could you help me with that thing?

2018-12-31 13:12 UTC, anandkansagra commented
> Well regarding that, took a pull from the remote 12.0 branch which has `crm_phonecall` module. In the runbot log, couldn't find why it has not passed. Could you help me with that thing?

Fixed

2019-04-15 19:38 UTC, tbaden requested changes
@anandkansagra thanks for your work.
I did a code review and here are some minor changes:

2019-04-15 19:38 UTC, tbaden commented on crm_phonecall_summary_predefined/__manifest__.py
> +    "website": "http://www.tecnativa.com",
please change the website to https://github.com/OCA/crm

2019-04-15 19:38 UTC, tbaden commented on crm_phonecall_summary_predefined/views/crm_phonecall_summary_view.xml
> +    <record id="summary_form" model="ir.ui.view">
record id pattern should be:
> For a view: <model_name>_view_<view_type>, where view_type is kanban, form, tree, search, ...

crm_phonecall_summary_view_form

2019-04-15 19:38 UTC, tbaden commented on crm_phonecall_summary_predefined/views/crm_phonecall_summary_view.xml
> +    <record id="summary_tree" model="ir.ui.view">
same as above

crm_phonecall_summary_view_tree

2019-04-15 19:38 UTC, tbaden commented on crm_phonecall_summary_predefined/views/crm_phonecall_summary_view.xml
> +    <record id="summary_search" model="ir.ui.view">
same as above

crm_phonecall_summary_view_search

2019-04-15 19:38 UTC, tbaden commented on crm_phonecall_summary_predefined/views/crm_phonecall_summary_view.xml
> +        id="summary_action"
> For an action: the main action respects <model_name>_action. Others are suffixed with _<detail>, where detail is an underscore lowercase string explaining the action (should not be long). This is used only if multiple actions are declared for the model.

crm_phonecall_summary_action

2019-04-15 19:38 UTC, tbaden commented on crm_phonecall_summary_predefined/views/crm_phonecall_summary_view.xml
> +        id="summary_menu"
> For a menu: <model_name>_menu

crm_phonecall_summary_menu

2019-04-15 19:38 UTC, tbaden commented on crm_phonecall_summary_predefined/views/crm_phonecall_summary_view.xml
> +        action="summary_action"
refactoring.
see above:
crm_phonecall_summary_action

2019-04-16 09:25 UTC, anandkansagra commented
> @anandkansagra thanks for your work.
> I did a code review and here are some minor changes:

@tbaden ,
I have made the changes.

2019-04-16 10:35 UTC, tbaden approved these changes
Code Review: LGTM

2019-04-16 11:48 UTC, pedrobaeza approved these changes

2019-04-16 11:48 UTC, merged