[12.0] crm_deduplicate_filter: Migration to 12.0
OCA/crm pull request #260
Opened 2019-03-21 16:38 UTC by victormmtorres

Need rebase as module missing `crm_deduplicate_acl` waiting for migration

cc @Tecnativa

2019-03-21 17:57 UTC, pedrobaeza requested changes
Next time is better to start with the lower dependencies module (`crm_deduplicate_acl`). Check how I have modified main comment for letting clear the dependency.

2019-03-21 17:57 UTC, pedrobaeza commented on crm_deduplicate_filter/readme/CONTRIBUTORS.rst
> +* Luis M. Ontalba <luis.martinez@tecnativa.com>
Include yourself here

2019-03-21 17:57 UTC, pedrobaeza commented on crm_deduplicate_filter/readme/USAGE.rst
> +.. image:: https://odoo-community.org/website/image/ir.attachment/5784_f2813bd/datas
Don't include this part, as this is old stuff that now it's auto-generated in the header.

2019-03-22 10:13 UTC, victormmtorres commented
@pedrobaeza I did the changes requested

2019-03-22 18:53 UTC, pedrobaeza commented
This should be moved and renamed the same as base module, but better to wait for the other to be ready.

2019-03-25 18:42 UTC, closed without merging