[MIG] crm_claim_code: Migration to 12.0
OCA/crm pull request #266
Opened 2019-05-04 22:20 UTC by elrodo1

2019-05-05 14:41 UTC, luistorresm requested changes
@elrodo1 

Please remove the file `crm_claim_code/.DS_Store`

Regards

2019-05-05 14:51 UTC, hugho-ad commented on crm_claim_code/__init__.py
> +            claim.code = sequence_model.next_by_code('crm.claim')
please, move these functions to a new hooks.py file then just import the names of the functions at __init__.py
like the following
`from .hooks import post_init_hook`

2019-05-05 15:38 UTC, hugho-ad commented on crm_claim_code/tests/test_crm_claim_code.py
> +        cls.crm_claim_model = cls.env['crm.claim']
Dont use built-in variables
cls is a python reserved variable

2019-05-05 15:48 UTC, hugho-ad commented on crm_claim_code/tests/test_crm_claim_code.py
> +        cls.crm_claim_model = cls.env['crm.claim']
for get it, o got confuse

2019-05-05 16:15 UTC, luisiniguezh commented on crm_claim_code/i18n/es.po
> +msgstr "Reclamación"
I think `Reclamo` would be a better translation

2019-05-05 16:15 UTC, luisiniguezh commented on crm_claim_code/i18n/es.po
> +msgstr "Número de reclamación"
*`Número de reclamo`

2019-05-07 13:23 UTC, max3903 approved these changes

2019-05-07 14:21 UTC, hugho-ad approved these changes

2019-05-09 16:02 UTC, merged