[MIG] crm_location_nuts: Migration to 12.0
OCA/crm pull request #270
Opened 2019-05-16 10:54 UTC by Tardo

Normal migration

2019-05-16 13:49 UTC, pedrobaeza approved these changes
It's curious that there's no commit history for 8.0 version

2019-05-16 13:52 UTC, Tardo commented
@pedrobaeza ummm i "fixup" some commits but after "Migration to 10.0" commit...

2019-05-16 13:54 UTC, pedrobaeza commented
My fault, it was created for that version.

2019-05-17 08:06 UTC, yajo requested changes

2019-05-17 08:06 UTC, Yajo commented on crm_location_nuts/models/crm_lead.py
> +    def onchange_state_id_crm_location_nuts(self):
`@onchange()` methods must be private:

```suggestion
    def _onchange_state_id_crm_location_nuts(self):
```

2019-05-17 09:08 UTC, Tardo commented on crm_location_nuts/models/crm_lead.py
> +    def onchange_state_id_crm_location_nuts(self):
Done, thx!

2019-05-17 09:13 UTC, yajo approved these changes

2019-05-17 10:02 UTC, chienandalu approved these changes
Code and functional review :+1:

2019-05-17 10:05 UTC, merged