Update crm_lead_view.xml
OCA/crm pull request #289
Opened 2019-07-30 11:44 UTC by salma-dammak

2019-07-30 12:32 UTC, salma-dammak commented
Add 'name' field to search view on 'view_crm_case_leads_filter'

2019-09-01 22:57 UTC, rafaelbn commented
This PR is the same of https://github.com/OCA/crm/pull/290

2019-09-02 07:20 UTC, keshrath reviewed
I'm not sure what you're trying to improve with this PR. There is already a name field in this SerachView and it is extended to search for code as well. 

https://github.com/odoo/odoo/blob/12.0/addons/crm/views/crm_lead_views.xml#L388

2019-09-02 07:40 UTC, oihane approved these changes
LGTM

2019-09-02 08:51 UTC, sbejaoui requested changes

2019-09-02 08:51 UTC, sbejaoui commented on crm_lead_code/views/crm_lead_view.xml
> +                    <field name="name"/>
Field name is already in the search view, why you need to add it twice?

2022-02-27 12:29 UTC, closed without merging