[WIP][13.0][MIG] crm_lead_code
OCA/crm pull request #296
Opened 2019-09-30 09:42 UTC by murtuzasaleh

WIP

2019-09-30 15:04 UTC, JayVora-SerpentCS commented on crm_lead_code/__manifest__.py
> +    "website": "http://www.odoomrp.com",
Website : https://github.com/OCA/crm

2019-10-01 12:13 UTC, Swapnesh-SerpentCS commented on crm_lead_code/__manifest__.py
> +        "data/lead_sequence.xml",
data should be first

2019-10-01 12:14 UTC, Swapnesh-SerpentCS commented on crm_lead_code/models/crm_lead.py
> +                vals['code'] = self.env['ir.sequence'].next_by_code('crm.lead')
IMO we should use `next_by_id` here

2019-10-01 12:16 UTC, Swapnesh-SerpentCS commented on crm_lead_code/models/crm_lead.py
> +        default['code'] = self.env['ir.sequence'].next_by_code('crm.lead')
Instead of assigning  `default['code'] ` cant we add `copy=False` on field. (Which will automatically update code on copy )

2019-10-01 14:10 UTC, JayVora-SerpentCS approved these changes

2019-10-01 14:10 UTC, JayVora-SerpentCS commented on crm_lead_code/__manifest__.py
> +    "website": "http://www.odoomrp.com",
https://github.com/OCA/crm

2019-10-01 14:10 UTC, JayVora-SerpentCS commented on crm_lead_code/models/crm_lead.py
> +    @api.returns('self', lambda value: value.id)
Remove all the decorators @api.multi, @api.returns, @api.one from the code, as now they are all multi-record by default. In case of the last one, you will need to adapt the code to the behavior change.

2020-05-04 15:44 UTC, HaraldPanten commented
Hi @murtuzasaleh ,

Could you check travis, please?

2020-05-05 17:33 UTC, HaraldPanten approved these changes
Functional review. LGTM 👍

2020-05-12 12:38 UTC, skeller1 requested changes

2020-05-12 12:38 UTC, skeller1 commented on crm_lead_code/__manifest__.py
> +    "author": "Tecnativa, " "AvanzOSC, " "Odoo Community Association (OCA)",
Please fix the pre-commit error with `"`

2020-05-12 12:38 UTC, skeller1 commented on crm_lead_code/static/description/index.html
> +<meta name="generator" content="Docutils 0.14: http://docutils.sourceforge.net/" />
Please (re)generate the docs

2020-06-16 15:08 UTC, mamcode approved these changes
LGTM.

2020-06-16 15:15 UTC, mamcode commented
This PR has enough approvals, it should be merged soon... @OCA/crm-sales-marketing-maintainers

2020-06-16 15:36 UTC, Swapnesh-SerpentCS approved these changes

2020-06-18 05:21 UTC, simahawk commented
/ocabot merge nobump

2020-06-18 09:21 UTC, merged