[13.0][MIG] crm_phonecall: Migration to 13.0
OCA/crm pull request #306
Opened 2020-02-11 12:35 UTC by Tardo

cc @tecnativa TT21623

2020-02-15 17:25 UTC, MeetKD requested changes

2020-02-15 17:25 UTC, MeetKD commented on crm_phonecall/__manifest__.py
> +    "website": "https://www.tecnativa.com",
website - > https://github.com/OCA/crm

2020-02-15 17:28 UTC, MeetKD requested changes

2020-02-15 17:28 UTC, MeetKD commented on crm_phonecall/models/crm_phonecall.py
> +    date = fields.Datetime(default=fields.Datetime.now)
```suggestion
    date = fields.Datetime(default=lambda self: fields.Datetime.now())
```

2020-02-17 18:40 UTC, ernestotejeda requested changes
Thanks @Tardo 
For me, functionally OK

2020-02-17 18:40 UTC, ernestotejeda commented on crm_phonecall/README.rst
> +#. Go to *Sales > Phone Calls > Logged Calls > Create*.
```suggestion
#. Go to *CRM > Phone Calls > Logged Calls > Create*.
```

2020-02-17 18:40 UTC, ernestotejeda commented on crm_phonecall/README.rst
> +#. Calls can be analyzed in *Sales > Reports > Phone Calls Analysis*.
```suggestion
#. Calls can be analyzed in *CRM > Reports > Phone Calls Analysis*.
```

2020-02-17 19:31 UTC, Tardo commented
Changes done. Thanks!

2020-02-17 20:53 UTC, ernestotejeda approved these changes

2020-02-26 07:16 UTC, pedrobaeza commented
Please squash a bit administrative commits

2020-02-26 13:24 UTC, ernestotejeda approved these changes

2020-02-26 14:15 UTC, Tardo commented
Umm the commit history shown here doesn't match with the history that i can see in local :/

In local I see '80445e2', '13eb848', '4edc63c', '9278420' and 'ebf1da0' before '527db1e'.
And these commits appears to be related with other module: crm_stage_probability

2020-02-27 15:55 UTC, Tardo commented
Conflicts resolved

2020-02-27 16:02 UTC, sergio-teruel commented
Thanks!!!

2020-02-28 07:28 UTC, pedrobaeza commented
About squashing administrative commits I mean:
![Selección_064](https://user-images.githubusercontent.com/7165771/75519773-490a4400-5a04-11ea-96b6-f9bb5961c47c.png)

2020-03-02 13:55 UTC, Tardo commented
Done!

2020-03-02 16:36 UTC, pedrobaeza commented
/ocabot merge

2020-03-02 16:59 UTC, merged