14.0 mig crm claim type
OCA/crm pull request #371
Opened 2020-11-15 17:04 UTC by redapureskill

Migrating crm claim type from V13 to **V14**
======

2020-11-15 17:15 UTC, redapureskill commented
Waiting for crm_claim v14 to be merged, it's on #370

2021-05-31 13:47 UTC, redapureskill commented
LGTM

2021-08-31 22:34 UTC, omar7r commented
Hi @redapureskill please, can you rebase it for testing?

2021-09-09 08:44 UTC, fredzamoabg requested changes

2021-09-09 08:44 UTC, fredzamoabg commented on crm_claim/README.rst
> +Claims Management
module `crm_claim` is already merged in 14.0 (https://github.com/OCA/crm/pull/391)
can you please remove from this PR?

2021-09-09 08:44 UTC, fredzamoabg commented on crm_claim_type/views/crm_claim_type.xml
> +        groups="base.group_no_one"
can you include this information in README? otherwise is not clear how to see this menu

2022-04-17 12:32 UTC, closed without merging