[14.0][MIG] crm_project: Migration to 14.0
OCA/crm pull request #403
Opened 2021-10-08 07:30 UTC by victoralmau

Migration to 14.0

Please @pedrobaeza and @joao-p-marques can you review it?

@Tecnativa TT30261

2021-10-08 12:18 UTC, pedrobaeza requested changes
It seems this wizard is only accessible from leads view, but it would be very interesting to have it also on opportunities view.

2021-10-08 12:18 UTC, pedrobaeza commented on crm_project/wizard/crm_lead_convert2task.py
> +        partner_id = lead._find_matching_partner()
It should be `partner`, isn't it?

2021-10-08 12:18 UTC, pedrobaeza commented on crm_project/wizard/crm_lead_convert2task.py
> -    _inherit = "crm.partner.binding"
Are we losing partner creation on the fly in this case?

2021-10-08 12:18 UTC, pedrobaeza commented on crm_project/security/ir.model.access.csv
> +access_crm_lead_convert2task,access_crm_lead_convert2task,model_crm_lead_convert2task,project.group_project_user,1,1,1,1
The one that should have permission is the sales users, not project ones.

2021-10-08 12:18 UTC, pedrobaeza commented on crm_project/__manifest__.py
> -    "sequence": "19",
Why removing this sequence? I would leave it, as it should have any meaning (like the module loading order). It's a pity to not have any comment about the why.

2021-10-08 12:25 UTC, victoralmau commented on crm_project/wizard/crm_lead_convert2task.py
> -    _inherit = "crm.partner.binding"
This model has been removed in v14.
`_find_matching_partner()` function (which is now in `crm.lead`), `_partner_assignment()` function also takes care of creating the partner if necessary.

2021-10-08 12:33 UTC, victoralmau commented on crm_project/__manifest__.py
> -    "sequence": "19",
OK, I keep it then even though we don't know the reason for this need.

2021-10-08 15:23 UTC, victoralmau commented
Changes made.
Form (`crm.crm_lead_view_form`) view is the same for opportunities and leads.

2021-10-08 15:54 UTC, pedrobaeza approved these changes
The sequence thing comes from the original Odoo module:

https://github.com/odoo/odoo/blame/12.0/addons/crm_project/__manifest__.py#L6

But no clue why

2021-10-14 09:40 UTC, CarlosRoca13 approved these changes

2021-10-14 09:41 UTC, pedrobaeza commented
/ocabot merge nobump

2021-10-14 10:06 UTC, merged