[14.0][MIG] crm_phonecall_summary_predefined: Migration to 14.0
OCA/crm pull request #431
Opened 2022-08-11 11:13 UTC by victoralmau

Migration to 14.0

Please  @CarlosRoca13 and @cesar-tecnativa can you review it?

@Tecnativa TT35390

2022-08-11 11:45 UTC, cesar-tecnativa requested changes

2022-08-11 11:45 UTC, cesar-tecnativa commented on crm_phonecall_summary_predefined/i18n/es.po
> +msgstr ""
missing translation

2022-08-11 11:45 UTC, cesar-tecnativa commented on crm_phonecall_summary_predefined/models/crm_phonecall.py
> +    name = fields.Char()
name should be required due to sql constraint

2022-08-11 11:45 UTC, cesar-tecnativa commented on crm_phonecall_summary_predefined/wizard/crm_phonecall_to_phonecall.py
> +        for phonecall in self.env["crm.phonecall"].browse(
you should ask for active_movel

2022-08-11 12:02 UTC, CarlosRoca13 approved these changes

2022-08-11 15:17 UTC, victoralmau commented
Changes done.

2022-08-11 17:26 UTC, cesar-tecnativa requested changes

2022-08-11 17:26 UTC, cesar-tecnativa commented on crm_phonecall_summary_predefined/wizard/crm_phonecall_to_phonecall.py
> +        model = self.env.context.get("active_model")
if model == 'crm.phonecall': 
        phonecall = self.env[model].browse(self.env.context.get("active_id"))
        res["summary_id"] = getattr(phonecall, "summary_id").id

2022-08-12 07:59 UTC, victoralmau commented
Changes done

2022-08-12 08:30 UTC, cesar-tecnativa approved these changes

2022-08-15 09:31 UTC, pedrobaeza commented
/ocabot migration crm_phonecall_summary_predefined
/ocabot merge nobump

2022-08-15 09:55 UTC, merged