[17.0][MIG] crm_project_task: Migration to 17.0
OCA/crm pull request #545
Opened 2024-01-31 14:44 UTC by mde-spring

2024-06-11 06:59 UTC, EmilioPascual commented
@mde-spring can you make rebase to launch runboat again, please? Thank you

2024-06-11 09:14 UTC, EmilioPascual requested changes

2024-06-11 09:14 UTC, EmilioPascual commented on crm_project_task/wizards/crm_create_task.py
> +                "<a href=# data-oe-model=crm.lead data-oe-id=%(lead)d>%(name)s</a>.",
Link in message post is not working properly
![image](https://github.com/OCA/crm/assets/53056345/c66f1f42-f78e-47f4-bff7-e2dd5bf0782e)

2024-06-11 09:14 UTC, EmilioPascual commented on crm_project_task/wizards/crm_create_task.py
> +                "data-oe-id=%(task)d>%(name)s</a> created.",
Same as before
![image](https://github.com/OCA/crm/assets/53056345/90b1a8e7-b096-443a-acec-ba89faf40cf2)

2024-10-28 05:45 UTC, zamberjo commented
Hi @mde-scopea, can you rebase and resolve conflicts?

2025-01-08 12:36 UTC, rousseldenis commented
/ocabot migration crm_project_task

2025-01-08 12:37 UTC, rousseldenis commented
/ocabot rebase

2025-01-08 12:37 UTC, rousseldenis commented
@mde-scopea Could you rebase ?

2025-01-15 09:09 UTC, mde-scopea commented
@rousseldenis rebase done including fixes on text in the note
Tests failed due to module crm_salesperson_planner

2025-01-27 17:20 UTC, EmilioPascual commented
> @rousseldenis rebase done including fixes on text in the note Tests failed due to module crm_salesperson_planner

Errors in chatter messages are still present.
![image](https://github.com/user-attachments/assets/d276bcf9-c163-49b7-b585-f48be6667300)

![image](https://github.com/user-attachments/assets/41e89ac3-3190-40d3-b290-665405ff330e)

2025-01-31 13:25 UTC, mide-dynapps commented
@EmilioPascual sorry, it's fixed now.

2025-02-14 08:50 UTC, EmilioPascual commented
> @EmilioPascual sorry, it's fixed now.

Yes, finally it's fixed, thank you @mde-scopea.

Now there are some errors with pre-commit. Can you fixed them?

2025-02-14 13:03 UTC, mide-dynapps commented
@EmilioPascual precommit fixed
Errors are due to another modules

2025-03-08 16:47 UTC, EmilioPascual commented
Errors in tests will be fixed in https://github.com/OCA/crm/pull/633

2025-03-10 09:00 UTC, EmilioPascual commented
https://github.com/OCA/crm/pull/633 is already merged. @mde-scopea can you rebase again? Now tests should be ok.

2025-03-11 16:53 UTC, mide-dynapps commented
@EmilioPascual done

2025-03-11 19:26 UTC, EmilioPascual approved these changes

2025-03-11 19:26 UTC, EmilioPascual commented
/ocabot merge patch

2025-03-13 16:14 UTC, EmilioPascual commented
@OCA/crm-sales-marketing-maintainers can you review this PR and merge if it's right?
I believed I could merge if I'm maintainer of the module, but something was wrong.

2025-03-25 13:51 UTC, rafaelbn approved these changes
/ocabot merge patch

2025-03-25 13:57 UTC, merged