[17.0][MIG] crm_stage_probability: Migration to 17.0
OCA/crm pull request #549
Opened 2024-02-29 17:12 UTC by MohamedOsman7

2024-03-04 12:26 UTC, CRogos reviewed
I think we can squash these commits into the migration 14.0 commit:
![image](https://github.com/OCA/crm/assets/1799080/605b5e41-db12-4800-8b8d-d29a7e4beaa0)

2024-03-04 12:26 UTC, CRogos commented on crm_stage_probability/views/crm_lead.xml
> +                position="after"
I think this should stay before and should look like this
![image](https://github.com/OCA/crm/assets/1799080/6db66530-167c-4e91-9a86-88dbb05c9a46)

2024-03-04 12:26 UTC, CRogos commented on crm_stage_probability/views/crm_lead.xml
>                      class="ps-0 ps-md-2 btn btn-link"
Could you check if this class fixes the layout.
`class="btn d-inline-block px-2 py-0 btn-link"`

2024-03-18 15:35 UTC, CRogos approved these changes

2024-05-07 13:58 UTC, MohamedOsman7 commented
@remi-filament could you please review?

2024-05-14 14:03 UTC, remi-filament requested changes
Hi @MohamedOsman7 thank you for porting this module.
I get a warning when installing : 
`WARNING odoo17 py.warnings: /opt/odoo/addons/base/models/ir_module.py:178: DeprecationWarning: XML declarations in HTML module descriptions are deprecated since Odoo 17, crm_stage_probability can just have a UTF8 description with not need for a declaration.`
I think you need to remove the xml tags (first line of index.html)

2024-05-14 14:05 UTC, remi-filament requested changes

2024-05-14 14:05 UTC, remi-filament commented on crm_stage_probability/static/description/index.html
> +<?xml version="1.0" encoding="utf-8"?>
```suggestion

```

2024-05-14 14:19 UTC, MohamedOsman7 commented
@remi-filament done

2024-05-14 15:03 UTC, remi-filament approved these changes
Thanks @MohamedOsman7 LGTM

2024-05-14 15:11 UTC, pedrobaeza commented
/ocabot migration crm_stage_probability
/ocabot merge nobump

2024-05-14 15:15 UTC, merged