[17.0][MIG] marketing_crm_partner: Migration to 17.0
OCA/crm pull request #603
Opened 2024-11-05 14:14 UTC by MohamedOsman7

2024-11-05 14:19 UTC, MohamedOsman7 commented
@flotho Could you please make a review?

2024-11-05 14:38 UTC, CRogos approved these changes
Code + Test LGTM

2024-11-19 12:09 UTC, MohamedOsman7 commented
@peluko00 @ppyczko could you please also here make a review

2024-11-19 13:35 UTC, peluko00 commented on marketing_crm_partner/README.rst
> +
The images don't load correctly

2024-11-19 14:46 UTC, CRogos commented on marketing_crm_partner/README.rst
> +
I think as soon as the PR is merged, the images should be visible. The images point to the 17.0 repo, which should be correct in my opinion.

2024-11-19 15:26 UTC, peluko00 approved these changes
LGTM, code review and tested in runboat

2024-11-20 06:24 UTC, ppyczko approved these changes
LGTM 👍

2024-11-20 07:10 UTC, pedrobaeza requested changes
There are new images in SVG that shouldn't be in that format, but PNG, and corresponding to enterprise snapshots. They should be in community version.

2024-11-20 12:48 UTC, MohamedOsman7 commented
@pedrobaeza Thanks for the hint. I made the requested changes.

2024-11-20 12:50 UTC, pedrobaeza approved these changes
Thank you for the changes

/ocabot migration marketing_crm_partner
/ocabot merge nobump

2024-11-20 12:55 UTC, merged