[MIG] crm_lead_to_task: Migration to 18.0
OCA/crm pull request #611
Opened 2024-11-27 09:39 UTC by HeliconiaSolutions

2025-04-01 06:11 UTC, victoralmau requested changes

2025-04-01 06:11 UTC, victoralmau commented on crm_lead_to_task/tests/test_crm_lead_task.py
> +        super().setUp()
```suggestion
from odoo.addons.base.tests.common import BaseCommon


class TestCrmLeadTask(BaseCommon):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
```

2025-04-01 09:10 UTC, BhaveshHeliconia commented
@victoralmau, Please Review.it's done.

2025-04-01 09:37 UTC, victoralmau approved these changes
Code and functional review OK

2025-06-27 13:42 UTC, victoralmau commented
Ping @pedrobaeza

2025-06-27 15:19 UTC, marcelsavegnago approved these changes
LGTM

2025-06-27 15:57 UTC, pedrobaeza commented on crm_lead_to_task/__manifest__.py
> +    "version": "18.0.1.1.0",
```suggestion
    "version": "18.0.1.0.0",
```

2025-06-27 15:58 UTC, pedrobaeza commented
/ocabot migration crm_lead_to_task

2025-07-01 11:04 UTC, BhaveshHeliconia commented on crm_lead_to_task/__manifest__.py
> +    "version": "18.0.1.1.0",
@pedrobaeza : it's done. Thanks for your input!

2025-07-01 11:07 UTC, pedrobaeza approved these changes
/ocabot merge nobump

2025-07-01 11:13 UTC, merged